#! /bin/sh

#starting Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

#defining workspaces
bspc monitor -d 1 2 3 4     

#border and gap
bspc config border_width         0
bspc config window_gap           8

#split,border color
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_frame_opacity 0.0
bspc config focused_border_color "#ff0d41"
bspc config ignore_ewmh_focus true 
bspc config removal_adjustment   true

#window rules
bspc rule -a Gcolor3 state=floating
bspc rule -a float state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating
# -------------------------
bspc rule -a qBittorrent  desktop=^4 follow=off
bspc rule -a mpv  desktop=^2 follow=on
bspc rule -a ranger  desktop=^2 follow=on
bspc rule -a discord  desktop=^4 follow=off
bspc rule -a xdman-Main  desktop=^4 follow=on
bspc rule -a obs  desktop=^4 follow=on
bspc rule -a "VirtualBox Manager"  desktop=^4 follow=on
# --------------------------
bspc config external_rules_command  ~/.config/bspwm/rule.sh


## starting apps
## -------------

# Screenshot
pkill flameshot
flameshot &

# Sudo manager
lxpolkit &

# Power manager
xfce4-power-manager &

# Cursor
xsetroot -cursor_name left_ptr &

# Wallpaper
$HOME/.config/bspwm/autostart/Desktop.sh

#notification 
dunst &

# Polyabr
$HOME/.config/polybar/mybar/launch.sh

#Picom
$HOME/.config/bspwm/autostart/picom.sh

# Clip-Board Manager 
$HOME/.config/bspwm/autostart/greenclip.sh

# Remapping Capslock
xmodmap ~/.Xmodmap

# Control mpris Player
playerctld &
