#! /bin/sh

# starting Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# defining workspaces
bspc monitor -d 1 2 3 4

# border and gap
bspc config border_width         0
bspc config window_gap           8

# split,border color
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_frame_opacity 0.0
bspc config focused_border_color "#3281ea"
bspc config normal_border_color  "#0d0d0d"
bspc config ignore_ewmh_focus true
bspc config removal_adjustment  true

# window rules
bspc rule -a Gcolor3 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a float state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a qBittorrent  desktop=^4 follow=off
bspc rule -a mpv  desktop=^2 follow=on
bspc rule -a discord  desktop=^4 follow=off
bspc rule -a xdman-Main  desktop=^4 follow=off
bspc rule -a obs  desktop=^5 follow=off
bspc rule -a "VirtualBox Manager"  desktop=^4 follow=on
bspc config external_rules_command  ~/.config/bspwm/rule.sh

# Sudo manager
lxpolkit &

# Cursor
xsetroot -cursor_name left_ptr &

# Wallpaper
$HOME/.config/bspwm/autostart/Desktop.sh

# notification
dunst &

# Polyabr [statusbar]
$HOME/.config/polybar/launch.sh

# Picom [compositor]
$HOME/.config/bspwm/autostart/picom.sh

# Clip-Board Manager
$HOME/.config/bspwm/autostart/greenclip.sh

# Remapping Capslock
xmodmap ~/.Xmodmap

# Mpris Players
$HOME/.config/bspwm/autostart/mpris.sh
