#!/bin/sh
if ! mpc >/dev/null 2>&1; then
  echo No Chill
  exit 1
elif mpc status | grep -q playing; then
  ( mpc current -f '%title%' | zscroll --before-text "" --delay .5 -l 30 --match-command "mpc status" --match-text "playing" "--before-text ''" --match-text "paused" "--before-text '' --scroll 0" --update-check true "mpc current -f '%title%'") &
else
  echo Not Playing
fi
# Block until an event is emitted
mpc idle >/dev/null
