#!/bin/sh

# update database
sudo rm /var/lib/pacman/db.lck &> /dev/null;yay -Sy &> /dev/null

if ! updates_arch=$(pacman -Qu 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ! updates_aur=$(yay -Qum 2> /dev/null | wc -l); then
# if ! updates_aur=$(paru -Qum 2> /dev/null | wc -l); then
# if ! updates_aur=$(cower -u 2> /dev/null | wc -l); then
# if ! updates_aur=$(trizen -Su --aur --quiet | wc -l); then
# if ! updates_aur=$(pikaur -Qua 2> /dev/null | wc -l); then
# if ! updates_aur=$(rua upgrade --printonly 2> /dev/null | wc -l); then
    updates_aur=0
fi

updates=$((updates_arch + updates_aur))

if [ "$updates" -gt 0 ]; then
    echo "%{o#010411}%{u#010411}%{B#004eff}%{F#000000}%{+u}%{+o} UP %{B- F- -u -o} $updates"
else
    echo "Wait"
fi
