-- Settings for Go
require('go').setup({
  go='go',
  goimport='gopls',
  fillstruct = 'gopls',
  gofmt = 'gofumpt',
  max_line_len = 120,
  tag_transform = false,
  gotests_template = "",
  gotests_template_dir = "",
  comment_placeholder = '' ,
  icons = {breakpoint = '🧘', currentpos = '🏃'},
  verbose = false,
  lsp_cfg = false,
  lsp_gofumpt = false,
  lsp_on_attach = nil,
  lsp_keymaps = true,
  lsp_codelens = true,
  lsp_diag_hdlr = true,
  lsp_diag_virtual_text = { space = 0, prefix = "" },
  lsp_diag_signs = true,
  lsp_diag_update_in_insert = false,
  lsp_document_formatting = true,
  gopls_cmd = nil,
  gopls_remote_auto = true,
  dap_debug = true,
  dap_debug_keymap = true,
  dap_debug_gui = true,
  dap_debug_vt = true,
  build_tags = "tag1,tag2",
  textobjects = true,
  test_runner = 'go',
  verbose_tests = true,
  run_in_floaterm = false,
})
