-- Lsp from non-servers
local null_ls = require("null-ls")
local sources = {
  null_ls.builtins.diagnostics.shellcheck,
  null_ls.builtins.code_actions.gitsigns,
  null_ls.builtins.formatting.reorder_python_imports,
  null_ls.builtins.formatting.prettier,
  null_ls.builtins.diagnostics.chktex,
  null_ls.builtins.diagnostics.codespell,
  null_ls.builtins.diagnostics.flake8,
  null_ls.builtins.diagnostics.pylint,
  null_ls.builtins.diagnostics.tsc,
  null_ls.builtins.diagnostics.proselint,
  null_ls.builtins.code_actions.proselint,
  null_ls.builtins.code_actions.shellcheck,
  null_ls.builtins.hover.dictionary,
  null_ls.builtins.formatting.autopep8,
  null_ls.builtins.formatting.black,
  null_ls.builtins.diagnostics.misspell,
  null_ls.builtins.formatting.asmfmt,
  null_ls.builtins.formatting.gofmt,
  null_ls.builtins.formatting.rustfmt,
  null_ls.builtins.formatting.eslint_d,
  null_ls.builtins.formatting.fixjson,
  null_ls.builtins.formatting.lua_format,
  null_ls.builtins.formatting.markdownlint,
  null_ls.builtins.diagnostics.eslint,
  null_ls.builtins.diagnostics.eslint_d,
  null_ls.builtins.diagnostics.markdownlint,
  null_ls.builtins.diagnostics.write_good,
  null_ls.builtins.code_actions.eslint,
  null_ls.builtins.code_actions.eslint_d,
}
null_ls.setup({ sources = sources })
